# Generated by Django 5.2.5 on 2025-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/images/'),
        ),
    ]
