# Generated by Django 5.2.5 on 2025-08-11 13:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vehicle_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
